### ISSUE TITLE
Post image not showing on individual post page

### ISSUE THREAD

**Issue by MattPfleger** [samuel-2004/AgileWebDevCITS3403#68]
![image](https://github.com/samuel-2004/AgileWebDevCITS3403/assets/161227771/c1541ee9-40df-4c65-9cce-cbb6ea2af0e4)

**Comment by Johnny-2003** [comment]
This has been resolved in the latest merge

**Comment by Johnny-2003** [comment]
Replies-default-image resolved this issue
